name = "McBingo"
author = "kinggeert, jordy_vogeltjes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a541b68644a94d99b00ae12299ecdd5e9f8f7d26592e9dd8ca7220e24e83488"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
