name = "McBingo"
author = "kinggeert, jordy_vogeltjes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4df01336e968b102ae353c4345d2949222f2f332dde3711abfdcfc4817bf3de"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
